version: '3.3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: app
  sut:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    environment:
      - RAILS_MASTER_KEY
    depends_on:
      - db
